### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by Ezorah** [KararTY/ServerAutoRecordArchiverHeroine#11]
Hi KararTY,

I think this is more of a feature request rather than an issue but I don't use github a lot and I'm not sure where else to put it.. Close this up if it's not the place for it. 

With the zipped backups, I'd like for the ability to combine them? I really enjoy the incremental backup feature using CRON but I don't like having more than one zip in the archive folder. I know myself or others will delete posts and that may mean a previous backup zip may have a post which the latest backup doesn't have. 

Alternatively the service could continually run and archive all posts as they're made?

Thanks for your hard work with this archiver, myself and i'm sure others really appreciate you putting the effort into making this.

**Comment by KararTY** [comment]
Hello Ezorah! This is certainly a feature request! 

So you want to take an initial complete guild archive, but then on future archives include **only** new messages? In any case you'd still have more ZIP files but these ZIP files, *after* the initial complete archive, would have smaller file sizes.

How does that sound?

**Comment by Ezorah** [comment]
Hey KararTY,

Thanks for the response :D 

That sounds great! I would be able to run the archive every 10 minutes without worrying about file size and it would catch messages which may be deleted later.

Maybe in the import feature of the S.A.R.A.H Viewer they could be combined in the view? I think in the current stage each zip file imported to view is separated into individual servers even though they're the same server (see uploaded picture)
![view](https://user-images.githubusercontent.com/36358052/36941461-de30c98c-1faf-11e8-958e-dea3643fca4a.png)


The viewer doesn't seem to work for me at the current moment, are there any dependencies?

My end goal is to be able to view complete chat history including messages that may have been deleted, any automated implementation of this is alright by me :D

**Comment by KararTY** [comment]
So I was right on, alright.

I wouldn't recommend having a 10 minute CRON schedule. That's 144 ZIP files every day depending on when you start running it.

How the upcoming "message deletion" feature would work is that it can only keep track of all new messages since script was run, this may be a Discord limitation or discord.js or whatever I'm not sure. 

This means the initial archive will contain all old conversations as well as possibly, now, deleted conversations. However, every new archive *after* the initial archive would keep track of new messages as well as newly deleted *new* messages by separating the two. Hope that's not confusing.

If you want to compact all later archives into one zip file, to load them into one view in the viewer, you'd have to do that manually by opening every zip file in the guild folder and then combining the individual files into one zip file. Don't worry about name file collisions, those should in theory not happen.

Just a heads up, the "message deletion" archive feature will not work unless one enables `auto` in `settings.js`.

Can you try [this link](https://kararty.github.io/SARAH/Viewer.html) and see if it works? It may need web workers which don't work in `file://` mode. If that still doesn't work, I'd appreciate it if you could take a screenshot, or [pastebin](https://pastebin.com), of the webkit console when clicking on one of the left-side icons? 
**P.S: Please use SARAH-Viewer's [issue tracker](https://github.com/kararty/sarah-viewer/issues) for any issues you have concerning the Viewer.**

Thanks, KararTY.

**Comment by KararTY** [comment]
#13 was just merged, bringing the requested features.
**More details here: #12**
